const $ = (selector) => document.querySelector(selector);
let session = null, latestSymptom = '';
const api = async (url, options = {}) => { const response = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); if (!response.ok) throw new Error((await response.json()).message || 'Request failed'); return response.status === 204 ? null : response.json(); };

$('#login-form').addEventListener('submit', async event => {
  event.preventDefault(); $('#login-error').textContent = '';
  try { session = await api('/api/login', {method:'POST', body:JSON.stringify({email:$('#email').value,password:$('#password').value,scope:document.querySelector('input[name=scope]:checked').value})}); localStorage.careLinkSession = JSON.stringify(session); startApp(); }
  catch(error) { $('#login-error').textContent = error.message; }
});
function startApp(){ $('#login-view').hidden=true; $('#app-view').hidden=false; $('#welcome').textContent=`Hello, ${session.user.name}`; if(session.scope==='patient'){ $('#patient-nav').hidden=false; showPatientTab('home'); } else { $('#doctor-view').hidden=false; loadDoctorAppointments(); } }
$('#logout').onclick=()=>{localStorage.removeItem('careLinkSession');location.reload()};
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>showPatientTab(button.dataset.tab));
function showPatientTab(tab){ document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); $('#patient-home').hidden=tab!=='home'; $('#patient-appointments').hidden=tab!=='my-appointments'; if(tab==='my-appointments') loadPatientAppointments(); }
$('#search-form').addEventListener('submit', async event=>{event.preventDefault();latestSymptom=$('#symptom').value;const result=await api('/api/doctors?symptom='+encodeURIComponent(latestSymptom));$('#suggestion').textContent=result.suggested_specialization ? `Suggested department: ${result.suggested_specialization}` : 'No exact match — showing all registered doctors.';$('#doctor-list').innerHTML=result.doctors.map(d=>`<article class="doctor-card"><h3>${d.name}</h3><p>${d.specialization} · ${d.hospital}</p><p>${d.city}</p><p class="rating">★ ${d.rating}/5</p><button onclick="openBooking('${d.id}','${d.name}')">Book appointment</button></article>`).join('') || '<p>No doctors found in this area.</p>';});
function openBooking(id,name){$('#booking-doctor-id').value=id;$('#booking-title').textContent=`Book with ${name}`;$('#booking-date').min=new Date().toISOString().split('T')[0];$('#booking-dialog').showModal()} window.openBooking=openBooking;
$('#booking-form').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/appointments',{method:'POST',body:JSON.stringify({patient_id:session.user.id,doctor_id:$('#booking-doctor-id').value,date:$('#booking-date').value,time:$('#booking-time').value,symptom:latestSymptom})});$('#booking-dialog').close();alert('Appointment booked successfully.');showPatientTab('my-appointments')}catch(error){alert(error.message)}});
function appointmentMarkup(a,doctor=false){const today=new Date().toISOString().split('T')[0];const queue=a.queue_position?` · Queue #${a.queue_position}`:'';return `<article class="appointment ${doctor&&a.date===today?'today':''}"><div><h3>${doctor?a.patient_name:a.doctor_name}</h3><p>${doctor?`${a.specialization} · ${a.symptom}`:`${a.specialization} · ${a.hospital}`}</p><p><b>${a.date}</b> at <b>${a.time}</b> · ${a.status}${queue}</p></div>${!doctor?`<div class="appointment-actions"><button onclick="editAppointment('${a.id}')">Edit</button><button class="delete" onclick="cancelAppointment('${a.id}')">Cancel</button></div>`:''}</article>`}
async function loadPatientAppointments(){const data=await api('/api/appointments?patient_id='+session.user.id);$('#patient-appointment-list').innerHTML=data.length?data.map(a=>appointmentMarkup(a)).join(''):'<p class="muted">You have no appointments yet.</p>'}
async function loadDoctorAppointments(){const data=await api('/api/appointments?doctor_id='+session.user.id);renderDoctor(data)}
function renderDoctor(data){const sort=$('#doctor-sort').value;data.sort((a,b)=>sort==='time'?a.time.localeCompare(b.time):`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));$('#doctor-appointment-list').innerHTML=data.length?data.map(a=>appointmentMarkup(a,true)).join(''):'<p class="muted">No appointments booked yet.</p>'}
$('#doctor-sort').onchange=loadDoctorAppointments;
async function cancelAppointment(id){if(confirm('Cancel this appointment?')){await api('/api/appointments/'+id,{method:'DELETE'});loadPatientAppointments()}} window.cancelAppointment=cancelAppointment;
async function editAppointment(id){const date=prompt('New date (YYYY-MM-DD):');const time=prompt('New time (HH:MM):');if(date&&time){await api('/api/appointments/'+id,{method:'PUT',body:JSON.stringify({date,time})});loadPatientAppointments()}} window.editAppointment=editAppointment;
try { session=JSON.parse(localStorage.careLinkSession); if(session) startApp(); } catch (_) { localStorage.removeItem('careLinkSession'); }
